"""
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
"""


# Solution 1: hashmap
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        cnt = [0] * 26
        
        for c in s:
            cnt[ord(c)-ord("a")] += 1
            
        for c in t:
            if cnt[ord(c)-ord("a")] == 0:
                return c
            else:
                cnt[ord(c)-ord("a")] -= 1
        
        return ""


# Solution 2: bit manipulation
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        res = 0
        
        for c in s:
            res ^= ord(c)
            
        for c in t:
            res ^= ord(c)
            
        return chr(res)
        